version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --providers.docker.swarmMode=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  kanboard:
    image: kanboard/kanboard:latest
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
    deploy:
      labels:
        - traefik.http.routers.kanboard-router.rule=Host(`192.168.0.231`)
        - traefik.http.services.kanboard-service.loadbalancer.server.port=80
      replicas: 2

volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl: